version: "3.4"
volumes:
  my-db:
services:
  selenium-grid:
    image: selenium/standalone-chrome 
    volumes:
      - "/dev/shm:/dev/shm"
    ports:
      - "4444:4444"
      - "5900:5900"
    networks:
      selenium_grid_net:
        ipv4_address: 172.20.20.2
    container_name: selenium-grid
    hostname: selenium
    depends_on:
      - database

  python-app:
    build:
      context: .
      dockerfile: python_Dockerfile
    image: python-selenium-tests:v1
    #    volumes:
    #  - "/home/dev/work/selenium/tests:/tests"
    networks:
      selenium_grid_net:
        ipv4_address: 172.20.20.3
      db_net:
        ipv4_address: 172.30.30.3
    container_name: python-app
    hostname: python
    depends_on:
      - selenium-grid
    command: bash -c "tail -f /dev/null"

  database:
    build:
      context: .
      dockerfile: mariadb_Dockerfile
    ports:
      - 3306:3306
    networks:
      db_net:
        ipv4_address: 172.30.30.2
    container_name: database
    hostname: mariadb
    command: bash -c "service mysql start; tail -f /dev/null"

networks:
  selenium_grid_net:
    ipam:
      config:
        - subnet: 172.20.20.0/24
  db_net:
    ipam:
      config:
        - subnet: 172.30.30.0/24

