version: "3.4"

services:
  selenium-grid:
    image: selenium/standalone-chrome 
    volumes:
      - "/dev/shm:/dev/shm"
    ports:
      - "4444:4444"
      - "5900:5900"
    networks:
      selenium_grid_net:
        ipv4_address: 172.20.20.2
    container_name: selenium-grid
    hostname: selenium

  python-app:
    build:
      context: .
    image: python-selenium-tests:v1
    volumes:
      - "/home/dev/work/selenium/tests:/tests"
    networks:
      selenium_grid_net:
        ipv4_address: 172.20.20.3
      db_net:
        ipv4_address: 172.30.30.3
    container_name: python-app
    hostname: python
    command: tail -f /dev/null

  database:
    image: mariadb:10.7
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=citizix_user
      - MYSQL_DATABASE=citizix_db
    networks:
      db_net:
        ipv4_address: 172.30.30.2
    container_name: database
    hostname: mariadb
    command: tail -f /dev/null

 
networks:
  selenium_grid_net:
    ipam:
      config:
        - subnet: 172.20.20.0/24
  db_net:
    ipam:
      config:
        - subnet: 172.30.30.0/24

